#!perl

use 5.010001;
use strict;
use warnings;

use Text::ANSITable;

my $t = Text::ANSITable->new;
$t->columns([qw/col1 col2/]);
$t->add_row([1, "one"]);
$t->add_row([2, "two"]);
$t->add_row([3, "three"]);
$t->add_row([4, "four"]);
$t->add_row([5, "five"]);
$t->add_row([6, "six"]);
$t->add_row([7, "seven"]);
$t->add_row([8, "eight"]);
$t->add_row([9, "nine"]);
$t->add_row([10, "ten"]);

$t->add_cond_row_style(
    sub {
        my ($self, %args) = @_;
        my $row_data = $args{row_data};
        $row_data->[0] % 2;
    },
    fgcolor => 'ff0000',
);

$t->add_cond_row_style(
    sub {
        my ($self, %args) = @_;
        my $row_data = $args{row_data};
        $row_data->[0] % 3 == 0;
    },
    bgcolor => '000080',
);

print $t->draw;

# ABSTRACT: Conditional row style

=head1 SYNOPSIS

 % ansitable-eg-style-01-conditional-row-style

=head1 DESCRIPTION

This example script shows how to use conditional row style. The conditional row
style adds a red foreground color for odd rows, and a blue background for every
third row.
